PAIN_DRIVEN_LANGUAGE = [
    "manual process",
    "manual workflows",
    "time consuming",
    "slow process",
    "slow workflow",
    "error prone",
    "prone to human error",
    "expensive",
    "high operational cost",
    "inefficient",
    "resource intensive",
    "labor intensive",
    "does not scale",
    "poor scalability",
    "legacy system",
    "outdated tools",
    "fragmented systems",
    "multiple tools",
    "tool sprawl",
    "data silos",
    "lack of visibility",
    "no real time insights",
    "limited insights",
    "delayed reporting",
    "slow decision making",
    "complex setup",
    "difficult to maintain",
    "hard to integrate",
    "integration challenges",
    "lengthy onboarding",
    "steep learning curve",
    "high training cost",
    "repetitive tasks",
    "redundant work",
    "low productivity",
    "operational bottlenecks",
    "workflow bottlenecks",
    "frequent failures",
    "downtime issues",
    "unreliable system",
    "poor user experience",
    "customer frustration",
    "missed opportunities",
    "compliance risk",
    "security concerns",
    "data inconsistency",
    "lack of automation",
]


OUTCOME_DRIVEN_LANGUAGE = [
    "reduce cost",
    "lower operational costs",
    "cost savings",
    "save time",
    "increase revenue",
    "boost revenue",
    "improve accuracy",
    "reduce errors",
    "faster turnaround",
    "faster processing",
    "speed up workflows",
    "increase efficiency",
    "improve productivity",
    "higher throughput",
    "optimize operations",
    "streamline processes",
    "automate workflows",
    "end manual work",
    "real time insights",
    "better decision making",
    "data driven decisions",
    "actionable insights",
    "improve visibility",
    "better tracking",
    "improved reporting",
    "scalable growth",
    "scale effortlessly",
    "handle higher volume",
    "improve reliability",
    "reduce downtime",
    "increase uptime",
    "better user experience",
    "improve customer satisfaction",
    "faster onboarding",
    "shorter learning curve",
    "simplify operations",
    "operational excellence",
    "competitive advantage",
    "faster time to value",
    "quick deployment",
    "measurable ROI",
    "predictable outcomes",
    "improved compliance",
    "enhanced security",
    "future proof solution",
    "long term savings",
    "sustainable growth",
]
BUZZWORD_POSITIONING = [
    "ai-powered",
    "ai-driven",
    "powered by artificial intelligence",
    "powered by machine learning",
    "ml-enabled",
    "deep learning based",
    "data-driven platform",
    "intelligent automation",
    "smart automation",
    "autonomous system",
    "self-learning system",
    "next generation",
    "next-gen technology",
    "future-ready platform",
    "cutting edge",
    "state of the art",
    "modern tech stack",
    "advanced analytics",
    "predictive analytics",
    "real-time intelligence",
    "end-to-end platform",
    "full stack solution",
    "one stop solution",
    "all-in-one platform",
    "unified solution",
    "seamless integration",
    "plug and play",
    "scalable architecture",
    "enterprise grade",
    "production ready",
    "cloud native",
    "api first",
    "microservices based",
    "built for scale",
    "highly scalable",
    "secure by design",
    "privacy first",
    "battle tested",
    "industry leading",
    "best in class",
    "innovation driven",
    "technology first",
    "digital transformation",
    "disruptive technology",
    "game changing platform",
    "revolutionary solution",
    "reimagining workflows",
]
